services:
  order-service:
    image: europe-west10-docker.pkg.dev/app-dynamics-demo/app-dynamics-container-registry/order-service:0.1.1
#    image: order-service:0.1.1
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
    environment:
      APPDYNAMICS_AGENT_NODE_NAME: "order-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  order-history-service:
    image: europe-west10-docker.pkg.dev/app-dynamics-demo/app-dynamics-container-registry/order-history-service:0.1.2
#    image: order-history-service:0.1.1
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres
    environment:
      APPDYNAMICS_AGENT_NODE_NAME: "order-history-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"
      - "29092:29092"

# temp unavailable
#  prometheus:
#    image: europe-west10-docker.pkg.dev/app-dynamics-demo/app-dynamics-container-registry/prometheus:0.1.0
#    depends_on:
#      - order-service
#      - order-history-service
#    ports:
#      - "8090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
