spring.application.name=order-history-service
server.port=8081

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.database=postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update